### ISSUE TITLE
Craw data when click to link.

### ISSUE THREAD

**Issue by vanloc0301** [virkillz/php-price-crawler#1]
I want to get the content of a news after the click to this link.

So, I tried with my code (this example using Goutte):

```
$crawler = $this->client->request('GET', 'http://giaitri.vnexpress.net');

$news = $crawler->filter('#news_home > li');
$link = null;
$news = $crawler->filter('#news_home > li')->each(function($node) {
    $link = $node->filter('.txt_link');
    $child_news = $this->client->click($link->link());
    print_r($child_news->filter('#left_calculator')->text());
    if(!empty($child_news->filter('#left_calculator'))) {
        return [
        'title' => $link->text(),
        'link'  => $link->link()->getUri(),
        'thumbnail' => $node->filter('.txt_link img')->attr('src'),
        'description' => trim($node->filter('.news_lead')->text()),
        'content' => trim($child_news->filter('#left_calculator')->text()),
        ];
    }
});
```

`print_r($child_news->filter('#left_calculator')->text())` have values.

But in an array:

`'content' => trim($child_news->filter('#left_calculator')->text()),`

I found in your project only get the content of URL.

In my case, I add an URL of news. This URL contain much news. I will scan it and be scrapping all content of a link.

Note: you should add the new database. 
Your database lost table `settings`

**Comment by virkillz** [comment]
Noted. This project is no longer maintained.
